chore: update dependencies to remove vulnerabilities
silvermine/serverless-plugin-cloudfront-lambda-edge pull request #71
Opened 2021-05-11 23:36 UTC by jimjenkins5

2021-05-19 14:30 UTC, yokuze requested changes
Just the one comment.

2021-05-24 14:14 UTC, jimjenkins5 commented on .editorconfig
> +[*]
Apparently this I did `ln {path}` instead of `ln -s {path}` 🤦

2021-05-24 14:14 UTC, jimjenkins5 commented
Back to you @yokuze

2021-05-26 12:41 UTC, jthomerson approved these changes

2021-05-26 12:41 UTC, merged

2021-05-26 12:41 UTC, jthomerson commented
I merged this, but @yokuze feel free to comment if you see anything else that needs to be addressed in a subsequent PR.

2021-05-26 12:47 UTC, jthomerson commented
Published in + @silvermine/serverless-plugin-cloudfront-lambda-edge@2.2.2

CC @yokuze @jimjenkins5